# Generated by Django 3.2.11 on 2022-01-14 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import interviewapp.validator


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start_time', models.DateTimeField(help_text='Time should be at least 60 mins before current time', validators=[interviewapp.validator.val_future_time])),
                ('end_time', models.DateTimeField(help_text='Time should atleast 60 minutes from start time', validators=[interviewapp.validator.val_future_end_time])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
